---
abstract: 'printf, sprintf & say all-in-1; safer & easier!'
author:
  - 'Linda Walsh (perl-diddler@tlinx.org)'
build_requires:
  mem: v0.3.2
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.82, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: P
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
  mem: v0.3.2
version: v1.1.2
